language: generic
os:
- linux
- osx
env:
  matrix:
  - TRAVIS_PYTHON_VERSION="3.6"
  - TRAVIS_PYTHON_VERSION="3.7"
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda3-latest"
sudo: false
jobs:
  include:
    - stage: lint
      os: linux
      script:
        - pip install flake8
        - make lint
    - &deploy
      stage: deploy
      if: tag=~ v.*$
      os: osx
      env: TRAVIS_PYTHON_VERSION=3.7
      script:
        - pip install twine wheel
        - python setup.py bdist_wheel
        - twine upload -u mcflugen -p$PYPI_PASS dist/*compaction*
    - <<: *deploy
      os: osx
      env: TRAVIS_PYTHON_VERSION=3.6
    - <<: *deploy
      os: linux
      env: TRAVIS_PYTHON_VERSION=3.7
    - <<: *deploy
      os: linux
      env: TRAVIS_PYTHON_VERSION=3.6

before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda create -n _testing python=$TRAVIS_PYTHON_VERSION
- source activate _testing
- conda info -a && conda list
install:
- pip install -e .
script:
- pip install pytest pytest-cov pytest-datadir pytest-benchmark coveralls
- pytest -vvv --cov=compaction --cov-report=xml:$(pwd)/coverage.xml
after_success: coveralls
