language: generic
os:
- linux
- osx
env:
  matrix:
  - PYTHON="3.8"
  - PYTHON="3.7"
  - PYTHON="3.6"
  global:
  - secure: If5+q1H1EQwEZrhYvQAGoYBaVTu1Bfkw+J5OrIY5CanuhLExXK1CLVHMKML2sZdMEHIOGhBYaeUqHlEVbvP94Wb8RobfL4NT5FjOfXk9zbiT3vRdAbgJzCVy2ervx6m4acZcnrn0LCu6FQW294M7DUEK77ZQJToj3Qy0ypWDwzijAN/wWD5NZWc8Kndg2yH76qBXCQO79S242/gryPq83dbjwVW79+uUCsmhKsV5r8MIKib0Xm6zbd8a5qLsSveTNlx6zNMaVadkZM6r7mKt6mk6pEZxuL8GWWUo0SntZCW3FNncO9SrTfC2uOsBRF3BWDIWZHVqcedkdahNsOkVr95rYk+XjeKj0alWY8RsBwGl1XWMIJAFEQdgVfy+wvccOB41ZZXwICaT8TKKGpY/Za97DJF1g6rU/PCojA578YCyBjrqng5X7nQh9FBS74VpItt2oHE3KnAwyTrcboatXL2z1lpeHenAK8+rijYzLY288MMzTXw4risaPEI32QxGtPlzymDCbIAJqi3tZ5dTRTbffEmSjmRp3aBer0gY2qajq7uKo4TLiqhOIpWeQZA/ncF2PUqbkFtkd9ZejcZakUoAZ8wsAhfUTvebVsWMf7A7g1BKrStNdlo8OnNX0soIMLUSzGACag8khHUOdSKYEEtxMQC2wW5diq3VC36HbKs=
sudo: false
jobs:
  include:
  - stage: lint
    os: linux
    script:
    - pip install flake8
    - make lint
  - stage: deploy
    if: tag=~ v.*$
    os: linux
    env: PYTHON=3.8
    script: &1
    - pip install twine wheel
    - python setup.py sdist
    - twine upload -u mcflugen -p$PYPI_PASS dist/*compaction*
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    curl -L https://micromamba.snakepit.net/api/micromamba/osx-64/latest | tar -xvj bin/micromamba
  else
    curl -L https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
  fi
- ./bin/micromamba shell init -s bash -p ~/micromamba
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    source $HOME/.bash_profile
  else
    source $HOME/.bashrc
  fi
- micromamba activate
- micromamba install python=$PYTHON pip mamba --yes -c conda-forge
- mamba info -a && mamba list
install:
- pip install -e .
script:
- pip install -r requirements-testing.txt
- pip install pytest pytest-cov pytest-datadir pytest-benchmark coveralls
- pytest -vvv --cov=compaction --cov-report=xml:$(pwd)/coverage.xml --mypy
after_success: coveralls
