name: compaction
channels:
  - conda-forge
dependencies:
- python
- black
- click
- flake8
- isort
- landlab
- numpy
- pandas
- pytest
- pytest-cov
- pytest-datadir
- pytest-benchmark
- pyyaml
- scipy
