{% set name = "compaction" %}
{% set version = "0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - scipy
    - pandas
    - pyyaml

test:
  commands:
    - compact -h
  imports:
    - compaction

about:
  summary: Compact a column of sediment.

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
